image:
  file: .gitpod.Dockerfile

tasks:
  - name: Initialise
    init: |
      bash ${GITPOD_REPO_ROOT}/bin/init.sh > /tmp/init.log 2>&1
      gp sync-done init

  - name: Run
    init: gp sync-await init
    command: bash ${GITPOD_REPO_ROOT}/bin/start.sh

ports:
  - name: Web App
    description: The main application web server
    port: 3000
    onOpen: open-browser
  - port: 4526-4559
    onOpen: ignore

github:
  prebuilds:
    # enable for the default branch
    master: true
    # enable for all branches in this repo
    branches: true
    # enable for pull requests coming from this repo
    pullRequests: true
    # enable for pull requests coming from forks
    pullRequestsFromForks: true
    # add a check to pull requests
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description
    addBadge: true
